### ISSUE TITLE
console.log("[HubSpot Forms] Could not render form.")

### ISSUE THREAD

**Issue by chadcrowell** [jordannbeattie/craftcms-hubspot-forms#1]
Hi there - I have the plugin connected to Hubspot, field created, and I can select a form in the entry edit page of the control panel. However, I am getting this message on the rendered page, and no other info as to why. There's nothing in the Craft logs I can find, and in Hubspot, all the API call logs show green dots as though successful. Any ideas what's going on? 

Craft 4.6.1, plugin 4.0.2

**Comment by jordannbeattie** [comment]
Hello! 

The plugin will output `[HubSpot Forms] Could not render form.` to the console if either the form was not passed to the render method or if there was an issue in retrieving the Portal ID. 

If the error message is actually being output on the page instead, this is something I haven't seen before. 

Can you check in `project.yaml` that the `hubspot-forms` settings has a valid `hsPortalId` property? This should match up to the account you created the private app for. 

Also check when passing your form field to the render method that the form field has a value. 
If you dump out your form field value, is it being set & read correctly? 

let me know how you get on!
